[package]
name = "bootc-imagectl"
version = "0.1.0"
edition = "2024"
rust-version = "1.98"
description = "Finalize and install composefs bootc images."
repository = "https://github.com/yeetypete/bootc-imagectl"
license = "MIT"
keywords = ["arch", "bootc", "composefs", "debian", "image"]
categories = ["command-line-utilities"]
publish = false

[workspace]
members = ["xtask"]

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
xshell = "0.2"

[workspace.lints.clippy]
dbg_macro = "warn"
exit = "warn"
pedantic = { level = "warn", priority = -1 }
print_stderr = "warn"
todo = "warn"

[workspace.lints.rust]
missing_debug_implementations = "warn"
unsafe_code = "forbid"

# The container tests, see tests/container/main.rs.
[[test]]
name = "container"
path = "tests/container/main.rs"
required-features = ["container"]

# The VM tests, see tests/vm/main.rs.
[[test]]
name = "vm"
path = "tests/vm/main.rs"
required-features = ["vm"]

[dependencies]
anyhow = { workspace = true }
cap-std-ext = { version = "5", features = ["fs_utf8"] }
clap = { workspace = true }
rustix = { version = "1", features = ["time"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uzers = { version = "0.12", default-features = false, features = ["cache"] }

[dev-dependencies]
indoc = "2"
uzers = { version = "0.12", default-features = false, features = ["mock"] }

[features]
container = []
vm = []

[lints]
workspace = true

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
