//! Finalize the rootfs and check the result.

use std::ffi::OsString;
use std::path::Path;
use std::process::Command;
use std::sync::LazyLock;

use anyhow::Result;
use bootc_imagectl::command::CommandRunExt;
use cap_std_ext::cap_std::ambient_authority;
use cap_std_ext::cap_std::fs::{Dir, MetadataExt};

/// Where run.sh mounts bootc-imagectl.
const BOOTC_IMAGECTL: &str = "/usr/libexec/bootc-imagectl";

/// The rootfs after `bootc-imagectl finalize` ran on it once.
pub(crate) static ROOT: LazyLock<Dir> = LazyLock::new(|| {
    assert!(
        Path::new("/run/.containerenv").exists() || Path::new("/.dockerenv").exists(),
        "refusing to finalize the host, run the e2e tests with `just test-e2e`"
    );
    Command::new(BOOTC_IMAGECTL)
        .arg("finalize")
        .run()
        .expect("finalize failed");
    Dir::open_ambient_dir("/", ambient_authority()).expect("opening /")
});

/// The sorted names in `dir`.
pub(crate) fn names(dir: &str) -> Result<Vec<OsString>> {
    let mut names: Vec<_> = ROOT
        .read_dir(dir)?
        .map(|entry| entry.map(|entry| entry.file_name()))
        .collect::<Result<_, _>>()?;
    names.sort();
    Ok(names)
}

#[test]
fn lays_out_toplevel() -> Result<()> {
    for (link, target) in [
        ("home", "var/home"),
        ("root", "var/roothome"),
        ("srv", "var/srv"),
        ("mnt", "var/mnt"),
        ("media", "run/media"),
        ("ostree", "sysroot/ostree"),
    ] {
        assert_eq!(ROOT.read_link(link)?, Path::new(target), "/{link}");
    }
    assert!(ROOT.is_dir("sysroot"));
    assert!(ROOT.is_dir("var"));
    assert!(names("boot/EFI/Linux")?.is_empty());

    let layout = ROOT.read_to_string("usr/lib/tmpfiles.d/bootc-imagectl-layout.conf")?;
    assert!(
        layout.contains("d /var/home 0755 root root -\n"),
        "{layout}"
    );
    assert!(
        layout.contains("d /var/roothome 0700 root root -\n"),
        "{layout}"
    );
    Ok(())
}

#[test]
fn patches_systemd_tmpfiles() -> Result<()> {
    assert!(!ROOT.exists("usr/lib/tmpfiles.d/home.conf"));
    let provision = ROOT.read_to_string("usr/lib/tmpfiles.d/provision.conf")?;
    assert!(!provision.contains(" /root"), "{provision}");
    assert!(!provision.contains("/var/roothome "), "{provision}");
    Ok(())
}

#[test]
fn records_var_in_tmpfiles() -> Result<()> {
    let var = ROOT.read_to_string("usr/lib/tmpfiles.d/bootc-imagectl-var-1.conf")?;
    assert!(
        var.starts_with("# Generated by bootc-imagectl. Do not edit.\n"),
        "{var}"
    );
    assert!(var.contains("L /var/mail - - - - spool/mail\n"), "{var}");
    assert!(
        var.contains("d /var/spool/mail 1777 root root -\n"),
        "{var}"
    );
    assert!(
        !var.contains(" /var/tmp "),
        "systemd declares /var/tmp\n{var}"
    );
    assert!(
        !var.contains(" /var/home "),
        "the layout declares /var/home\n{var}"
    );
    Ok(())
}

#[test]
fn empties_var() -> Result<()> {
    assert_eq!(names("var")?, ["lock", "run", "tmp"]);
    assert_eq!(ROOT.metadata("var/tmp")?.mode() & 0o7777, 0o1777);
    assert_eq!(ROOT.read_link("var/run")?, Path::new("../run"));
    assert_eq!(ROOT.read_link("var/lock")?, Path::new("../run/lock"));
    Ok(())
}

#[test]
fn removes_machine_identity() -> Result<()> {
    assert_eq!(ROOT.read("etc/machine-id")?, b"");
    assert!(!ROOT.exists("etc/fstab"));
    assert!(!ROOT.exists("etc/passwd-"));
    let ssh = names("etc/ssh")?;
    assert!(
        !ssh.iter()
            .any(|name| name.as_encoded_bytes().starts_with(b"ssh_host_")),
        "{ssh:?}"
    );
    Ok(())
}

#[test]
fn builds_initramfs() -> Result<()> {
    let [kver] = names("usr/lib/modules")?.try_into().expect("one kernel");
    let modules = format!("usr/lib/modules/{}", kver.display());
    assert!(ROOT.exists(format!("{modules}/modules.dep")));
    let initramfs = ROOT.metadata(format!("{modules}/initramfs.img"))?;
    assert!(initramfs.len() > 0);
    assert_eq!(initramfs.mode() & 0o7777, 0o600);
    Ok(())
}
