[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["env"] }
rand = "0.10"
rustix = { version = "1", features = ["process"] }
serde_json = { workspace = true }
xshell = { workspace = true }

[lints]
workspace = true
