//! Check what `bootc-imagectl finalize` wrote into the image.

use std::ffi::OsString;
use std::path::Path;
use std::process::Command;
use std::sync::LazyLock;

use anyhow::Result;
use bootc_imagectl::command::CommandRunExt;
use bootc_imagectl::distro::{self, PackageName};
use cap_std_ext::camino::Utf8Path;
use cap_std_ext::cap_std::fs::{Dir, MetadataExt};
use cap_std_ext::cap_std::{ambient_authority, fs_utf8};

/// The root of the image.
pub(crate) static ROOT: LazyLock<Dir> =
    LazyLock::new(|| Dir::open_ambient_dir("/", ambient_authority()).expect("opening /"));

/// The sorted names in `dir`.
pub(crate) fn names(dir: &str) -> Result<Vec<OsString>> {
    let mut names: Vec<_> = ROOT
        .read_dir(dir)?
        .map(|entry| entry.map(|entry| entry.file_name()))
        .collect::<Result<_, _>>()?;
    names.sort();
    Ok(names)
}

/// The tmpfiles.d entries finalize generated for /var.
pub(crate) fn var_tmpfiles() -> Result<String> {
    Ok(ROOT.read_to_string("usr/lib/tmpfiles.d/bootc-imagectl-var-1.conf")?)
}

/// The path of the image's UKI.
fn uki() -> Result<String> {
    let [name] = names("boot/EFI/Linux")?.try_into().expect("one UKI");
    Ok(format!("/boot/EFI/Linux/{}", name.display()))
}

/// The paths in the initramfs the UKI embeds.
pub(crate) fn initramfs_paths() -> Result<Vec<String>> {
    let listing = Command::new("lsinitrd").arg(uki()?).output_string()?;
    Ok(listing
        .lines()
        .flat_map(str::split_whitespace)
        .map(str::to_owned)
        .collect())
}

#[test]
fn lays_out_toplevel() -> Result<()> {
    for (link, target) in [
        ("home", "var/home"),
        ("root", "var/roothome"),
        ("srv", "var/srv"),
        ("mnt", "var/mnt"),
        ("media", "run/media"),
        ("ostree", "sysroot/ostree"),
    ] {
        assert_eq!(ROOT.read_link(link)?, Path::new(target), "/{link}");
    }
    assert!(ROOT.is_dir("sysroot"));
    assert!(ROOT.is_dir("var"));
    assert!(ROOT.is_dir("boot/EFI/Linux"));

    let layout = ROOT.read_to_string("usr/lib/tmpfiles.d/bootc-imagectl-layout.conf")?;
    assert!(
        layout.contains("d /var/home 0755 root root -\n"),
        "{layout}"
    );
    assert!(
        layout.contains("d /var/roothome 0700 root root -\n"),
        "{layout}"
    );
    Ok(())
}

#[test]
fn patches_systemd_tmpfiles() -> Result<()> {
    assert!(!ROOT.exists("usr/lib/tmpfiles.d/home.conf"));
    let provision = ROOT.read_to_string("usr/lib/tmpfiles.d/provision.conf")?;
    assert!(!provision.contains(" /root"), "{provision}");
    assert!(!provision.contains("/var/roothome "), "{provision}");
    Ok(())
}

#[test]
fn skips_declared_paths_in_var_tmpfiles() -> Result<()> {
    let var = var_tmpfiles()?;
    assert!(
        var.starts_with("# Generated by bootc-imagectl. Do not edit.\n"),
        "{var}"
    );
    assert!(
        !var.contains(" /var/tmp "),
        "systemd declares /var/tmp\n{var}"
    );
    assert!(
        !var.contains(" /var/home "),
        "the layout declares /var/home\n{var}"
    );
    Ok(())
}

#[test]
fn sets_up_tmp_run_and_lock_in_var() -> Result<()> {
    assert_eq!(ROOT.metadata("var/tmp")?.mode() & 0o7777, 0o1777);
    assert_eq!(ROOT.read_link("var/run")?, Path::new("../run"));
    assert_eq!(ROOT.read_link("var/lock")?, Path::new("../run/lock"));
    Ok(())
}

#[test]
fn removes_machine_identity() -> Result<()> {
    assert_eq!(ROOT.read("etc/machine-id")?, b"uninitialized\n");
    assert!(!ROOT.exists("etc/fstab"));
    assert!(!ROOT.exists("etc/passwd-"));
    let ssh = names("etc/ssh")?;
    assert!(
        !ssh.iter()
            .any(|name| name.as_encoded_bytes().starts_with(b"ssh_host_")),
        "{ssh:?}"
    );
    Ok(())
}

#[test]
fn boots_from_uki() -> Result<()> {
    let [kver] = names("usr/lib/modules")?.try_into().expect("one kernel");
    let kver = kver.display();
    assert_eq!(uki()?, format!("/boot/EFI/Linux/{kver}.efi"));
    let modules = format!("usr/lib/modules/{kver}");
    assert!(ROOT.exists(format!("{modules}/modules.dep")));
    assert!(!ROOT.exists(format!("{modules}/vmlinuz")));
    assert!(!ROOT.exists(format!("{modules}/initramfs.img")));
    Ok(())
}

#[test]
fn initramfs_resolves_users_through_nss_systemd() -> Result<()> {
    let paths = initramfs_paths()?;
    assert!(paths.iter().any(|path| path == "etc/nsswitch.conf"));
    assert!(
        paths
            .iter()
            .any(|path| path.ends_with("/libnss_systemd.so.2")),
        "no nss-systemd module in the initramfs"
    );
    assert!(
        paths.iter().any(|path| path
            .strip_prefix("usr/lib/userdb/")
            .is_some_and(|name| name.strip_suffix(".user").is_some())),
        "no user records in the initramfs"
    );
    Ok(())
}

#[test]
fn queries_packages_from_moved_database() -> Result<()> {
    let distro = distro::detect(&fs_utf8::Dir::from_cap_std(ROOT.try_clone()?))?;
    let bash: PackageName = "bash".parse()?;
    assert!(distro.is_installed(&bash)?);
    assert!(!distro.is_installed(&"no-such-package".parse()?)?);
    assert_eq!(
        distro.package_owning(Utf8Path::new("/usr/bin/bash"))?,
        Some(bash)
    );
    Ok(())
}
