//! Remove machine identity that package postinstalls generate at build time.
//! The machine identity must instead be generated on first boot.

use anyhow::{Context, Result};
use cap_std_ext::cap_std::fs::Dir;
use cap_std_ext::dirext::CapStdExtDirExt;
use tracing::debug;

use crate::distro::Distro;

/// Delete machine identity files generated by package postinstalls at image build time.
pub(crate) fn remove_machine_identity(root: &Dir, distro: &dyn Distro) -> Result<()> {
    debug!("removing machine identity");

    // systemd recommends the machine-id file should be empty for generic images.
    root.write("etc/machine-id", b"")
        .context("emptying /etc/machine-id")?;

    // Host keys must be unique per machine. sshd regenerates missing ones on
    // first boot.
    if let Some(ssh) = root.open_dir_optional("etc/ssh")? {
        for entry in ssh.entries()? {
            let name = entry?.file_name();
            if name.as_encoded_bytes().starts_with(b"ssh_host_") {
                ssh.remove_file(&name)
                    .with_context(|| format!("removing /etc/ssh/{}", name.display()))?;
            }
        }
    }

    // Unless the container runtime bind-mounted one, which is not part of
    // the image.
    if root.symlink_metadata_optional("etc/resolv.conf")?.is_some()
        && !root.is_mountpoint("etc/resolv.conf")?.unwrap_or_default()
    {
        root.remove_file("etc/resolv.conf")
            .context("removing /etc/resolv.conf")?;
    }

    // The fstab packages create at install time is just a placeholder.
    root.remove_file_optional("etc/fstab")?;

    // Utilities like useradd and groupadd leave behind backup files that are not
    // needed in the image.
    for name in ["passwd", "group", "shadow", "gshadow", "subuid", "subgid"] {
        root.remove_file_optional(format!("etc/{name}-"))?;
    }
    root.remove_file_optional("etc/.pwd.lock")?;

    distro.remove_machine_identity(root)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::rootfs;

    /// A distribution whose packages generate no machine identity files.
    #[derive(Debug)]
    struct NoIdentity;

    impl Distro for NoIdentity {
        fn name(&self) -> &'static str {
            "test"
        }

        fn remove_machine_identity(&self, _root: &Dir) -> Result<()> {
            Ok(())
        }
    }

    #[test]
    fn removes_build_time_identity() -> Result<()> {
        let root = rootfs()?;
        root.create_dir_all("etc/ssh")?;
        root.write("etc/machine-id", b"0123456789abcdef0123456789abcdef\n")?;
        root.write("etc/ssh/ssh_host_ed25519_key", b"secret")?;
        root.write("etc/ssh/ssh_host_ed25519_key.pub", b"public")?;
        root.write("etc/ssh/sshd_config", b"keep")?;
        root.write("etc/resolv.conf", b"")?;
        root.write("etc/fstab", b"")?;
        root.write("etc/passwd", b"root:x:0:0::/root:/bin/sh\n")?;
        root.write("etc/passwd-", b"backup")?;
        root.write("etc/.pwd.lock", b"")?;

        remove_machine_identity(&root, &NoIdentity)?;

        assert_eq!(root.read("etc/machine-id")?, b"");
        assert!(!root.exists("etc/ssh/ssh_host_ed25519_key"));
        assert!(!root.exists("etc/ssh/ssh_host_ed25519_key.pub"));
        assert!(root.exists("etc/ssh/sshd_config"));
        assert!(!root.exists("etc/resolv.conf"));
        assert!(!root.exists("etc/fstab"));
        assert!(root.exists("etc/passwd"));
        assert!(!root.exists("etc/passwd-"));
        assert!(!root.exists("etc/.pwd.lock"));
        Ok(())
    }

    #[test]
    fn creates_a_missing_machine_id() -> Result<()> {
        let root = rootfs()?;
        root.create_dir("etc")?;
        remove_machine_identity(&root, &NoIdentity)?;
        assert_eq!(root.read("etc/machine-id")?, b"");
        Ok(())
    }
}
