//! Remove machine identity that package postinstalls generate at build time.
//! The machine identity must instead be generated on first boot.

use anyhow::{Context, Result, ensure};
use cap_std_ext::cap_std::fs_utf8::Dir;
use cap_std_ext::dirext::{CapStdExtDirExt, CapStdExtDirExtUtf8};
use tracing::debug;

use crate::distro::Distro;

/// The content of /etc/machine-id that marks the next boot as the first.
const MACHINE_ID_UNINITIALIZED: &[u8] = b"uninitialized\n";

/// Delete machine identity files generated by package postinstalls at image build time.
pub(super) fn finalize(root: &Dir, distro: &dyn Distro) -> Result<()> {
    debug!("removing machine identity");

    // systemd treats `uninitialized` as a first boot. It generates the machine
    // ID and runs the units with `ConditionFirstBoot=yes`.
    root.write("etc/machine-id", MACHINE_ID_UNINITIALIZED)
        .context("resetting /etc/machine-id")?;

    // Host keys must be unique per machine. sshd regenerates missing ones on
    // first boot.
    if let Some(ssh) = root.open_dir_optional("etc/ssh")? {
        for entry in ssh.entries()? {
            let name = entry?.file_name()?;
            if name.starts_with("ssh_host_") {
                ssh.remove_file(&name)
                    .with_context(|| format!("removing /etc/ssh/{name}"))?;
            }
        }
    }

    let mounted = root.symlink_metadata_optional("etc/resolv.conf")?.is_some()
        && root
            .as_cap_std()
            .is_mountpoint("etc/resolv.conf")?
            .unwrap_or_default();
    ensure!(
        !mounted,
        "/etc/resolv.conf is mounted by the container runtime and cannot be removed. \
         help: with podman, run this step with RUN --network=none. With docker  \
         (where mounting cannot be disabled) make /etc/resolv.conf a symlink in an earlier step, e.g. to \
         ../run/systemd/resolve/stub-resolv.conf"
    );
    // The distribution's resolver creates it at boot.
    root.remove_file_optional("etc/resolv.conf")
        .context("removing /etc/resolv.conf")?;

    // The fstab packages create at install time is just a placeholder.
    root.remove_file_optional("etc/fstab")?;

    // Utilities like useradd and groupadd leave behind backup files that are not
    // needed in the image.
    for name in ["passwd", "group", "shadow", "gshadow", "subuid", "subgid"] {
        root.remove_file_optional(format!("etc/{name}-"))?;
    }
    root.remove_file_optional("etc/.pwd.lock")?;

    distro.remove_machine_identity(root)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::{TestDistro, rootfs};

    #[test]
    fn removes_build_time_identity() -> Result<()> {
        let root = rootfs()?;
        root.create_dir_all("etc/ssh")?;
        root.write("etc/machine-id", b"0123456789abcdef0123456789abcdef\n")?;
        root.write("etc/ssh/ssh_host_ed25519_key", b"secret")?;
        root.write("etc/ssh/ssh_host_ed25519_key.pub", b"public")?;
        root.write("etc/ssh/sshd_config", b"keep")?;
        root.write("etc/resolv.conf", b"")?;
        root.write("etc/fstab", b"")?;
        root.write("etc/passwd", b"root:x:0:0::/root:/bin/sh\n")?;
        root.write("etc/passwd-", b"backup")?;
        root.write("etc/.pwd.lock", b"")?;

        finalize(&root, &TestDistro::default())?;

        assert_eq!(root.read("etc/machine-id")?, MACHINE_ID_UNINITIALIZED);
        assert!(!root.exists("etc/ssh/ssh_host_ed25519_key"));
        assert!(!root.exists("etc/ssh/ssh_host_ed25519_key.pub"));
        assert!(root.exists("etc/ssh/sshd_config"));
        assert!(!root.exists("etc/resolv.conf"));
        assert!(!root.exists("etc/fstab"));
        assert!(root.exists("etc/passwd"));
        assert!(!root.exists("etc/passwd-"));
        assert!(!root.exists("etc/.pwd.lock"));
        Ok(())
    }

    #[test]
    fn removes_resolv_conf_symlink() -> Result<()> {
        let root = rootfs()?;
        root.create_dir("etc")?;
        root.symlink("../run/systemd/resolve/stub-resolv.conf", "etc/resolv.conf")?;
        finalize(&root, &TestDistro::default())?;
        assert!(root.symlink_metadata_optional("etc/resolv.conf")?.is_none());
        Ok(())
    }

    #[test]
    fn creates_missing_machine_id() -> Result<()> {
        let root = rootfs()?;
        root.create_dir("etc")?;
        finalize(&root, &TestDistro::default())?;
        assert_eq!(root.read("etc/machine-id")?, MACHINE_ID_UNINITIALIZED);
        Ok(())
    }
}
