//! Kernel arguments required in all images.

use anyhow::{Context, Result};
use cap_std_ext::cap_std::fs_utf8::Dir;

/// The kargs.d directory, relative to the rootfs.
const KARGS_DIR: &str = "usr/lib/bootc/kargs.d";

/// The kargs.d file.
const KARGS_FILE: &str = "10-bootc-imagectl.toml";

/// Mount the root read-write, so that /etc and /var are writable.
const KARGS: &str = "# Generated by bootc-imagectl. Do not edit.\nkargs = [\"rw\"]\n";

/// Write the kargs.d file.
///
/// # Errors
///
/// Fails if the file cannot be written.
pub(super) fn finalize(root: &Dir) -> Result<()> {
    root.create_dir_all(KARGS_DIR)
        .with_context(|| format!("creating /{KARGS_DIR}"))?;
    let path = format!("{KARGS_DIR}/{KARGS_FILE}");
    root.write(&path, KARGS)
        .with_context(|| format!("writing /{path}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::rootfs;

    #[test]
    fn mounts_root_read_write() -> Result<()> {
        let root = rootfs()?;
        finalize(&root)?;
        assert_eq!(
            root.read_to_string(format!("{KARGS_DIR}/{KARGS_FILE}"))?,
            "# Generated by bootc-imagectl. Do not edit.\nkargs = [\"rw\"]\n"
        );
        Ok(())
    }
}
