//! Lay out the filesystem as bootc expects.

use std::fmt::Write;

use anyhow::{Context, Result};
use cap_std_ext::cap_std::fs::Dir;
use cap_std_ext::dirext::CapStdExtDirExt;
use tracing::debug;

use super::tmpfiles::{self, Entry};

/// The toplevel layout of a bootc system as tmpfiles.d entries. The symlinks
/// are created in the image. The directories they point to are created at
/// boot by systemd. Note that bootc creates /sysroot/ostree itself.
const LAYOUT: &[Entry<'static>] = &[
    Entry::Symlink {
        path: "/home",
        target: "var/home",
    },
    Entry::Directory {
        path: "/var/home",
        mode: 0o755,
        user: "root",
        group: "root",
    },
    Entry::Symlink {
        path: "/root",
        target: "var/roothome",
    },
    Entry::Directory {
        path: "/var/roothome",
        mode: 0o700,
        user: "root",
        group: "root",
    },
    Entry::Symlink {
        path: "/srv",
        target: "var/srv",
    },
    Entry::Directory {
        path: "/var/srv",
        mode: 0o755,
        user: "root",
        group: "root",
    },
    Entry::Symlink {
        path: "/mnt",
        target: "var/mnt",
    },
    Entry::Directory {
        path: "/var/mnt",
        mode: 0o755,
        user: "root",
        group: "root",
    },
    Entry::Symlink {
        path: "/media",
        target: "run/media",
    },
    Entry::Directory {
        path: "/run/media",
        mode: 0o755,
        user: "root",
        group: "root",
    },
    Entry::Symlink {
        path: "/ostree",
        target: "sysroot/ostree",
    },
];

/// Lay out the toplevel directories and symlinks.
pub(crate) fn layout_toplevel(root: &Dir) -> Result<()> {
    debug!("laying out the toplevel");
    let mut entries = String::from("# Generated by bootc-imagectl. Do not edit.\n");
    for entry in LAYOUT {
        match entry {
            Entry::Symlink { path, target } => {
                let link = path.trim_start_matches('/');
                root.remove_all_optional(link)
                    .with_context(|| format!("removing {path}"))?;
                root.symlink(target, link)
                    .with_context(|| format!("linking {path} -> {target}"))?;
            }
            Entry::Directory { .. } => writeln!(entries, "{entry}")?,
        }
    }
    let path = format!("{}/bootc-imagectl-layout.conf", tmpfiles::USR_TMPFILES_DIR);
    root.create_dir_all(tmpfiles::USR_TMPFILES_DIR)?;
    root.write(&path, entries)
        .with_context(|| format!("writing /{path}"))?;

    // The composefs digest sealed into the UKI excludes the UKI itself but
    // not its parent directory, so the directory has to exist in the image.
    root.remove_all_optional("boot").context("removing /boot")?;
    root.create_dir_all("boot/EFI/Linux")
        .context("creating /boot/EFI/Linux")?;

    root.create_dir_all("sysroot")
        .context("creating /sysroot")?;
    root.create_dir_all("var").context("creating /var")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::*;
    use crate::testutil::rootfs;

    #[test]
    fn replaces_directories_and_stale_links_with_symlinks() -> Result<()> {
        let root = rootfs()?;
        root.create_dir_all("home/user")?;
        root.write("home/user/file", b"x")?;
        root.symlink("elsewhere", "srv")?;
        root.write("mnt", b"a regular file")?;

        layout_toplevel(&root)?;

        for entry in LAYOUT {
            if let Entry::Symlink { path, target } = entry {
                let link = path.trim_start_matches('/');
                assert_eq!(root.read_link(link)?, Path::new(target), "{path}");
            }
        }
        Ok(())
    }

    #[test]
    fn recreates_boot_and_creates_mount_points() -> Result<()> {
        let root = rootfs()?;
        root.create_dir_all("boot/EFI/Linux")?;
        root.write("boot/EFI/Linux/stale.efi", b"x")?;
        root.write("boot/vmlinuz", b"x")?;

        layout_toplevel(&root)?;

        assert!(root.is_dir("boot/EFI/Linux"));
        assert_eq!(root.read_dir("boot/EFI/Linux")?.count(), 0);
        assert_eq!(root.read_dir("boot")?.count(), 1);
        assert!(root.is_dir("sysroot"));
        assert!(root.is_dir("var"));
        Ok(())
    }

    #[test]
    fn writes_tmpfiles_for_directories() -> Result<()> {
        let root = rootfs()?;
        layout_toplevel(&root)?;
        let conf = root.read_to_string(format!(
            "{}/bootc-imagectl-layout.conf",
            tmpfiles::USR_TMPFILES_DIR
        ))?;
        for entry in LAYOUT {
            let line = entry.to_string();
            let written = conf.contains(&line);
            assert_eq!(
                written,
                matches!(entry, Entry::Directory { .. }),
                "{line}\n{conf}"
            );
        }
        Ok(())
    }

    #[test]
    fn is_idempotent() -> Result<()> {
        let root = rootfs()?;
        layout_toplevel(&root)?;
        layout_toplevel(&root)?;
        assert_eq!(root.read_link("home")?, Path::new("var/home"));
        Ok(())
    }
}
