//! Keep the units the image enables from being disabled on first boot.
//!
//! On the first boot, systemd applies the distribution's systemd.preset(5)
//! files to all units, which on some distributions (e.g. Fedora) also
//! disables the units they do not enable. `bootc-imagectl finalize`
//! generates a preset file that sorts before the distribution's and enables
//! them, ensuring that they stay enabled after the first boot.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

use anyhow::{Context, Result};
use cap_std_ext::cap_std::fs_utf8::Dir;
use cap_std_ext::dirext::CapStdExtDirExtUtf8;
use tracing::{debug, info};

use super::units::{self, EnablementState, Preset, UnitFile, UnitName};

/// Where packages install their system preset files.
const PRESET_DIR: &str = "usr/lib/systemd/system-preset";

/// The generated preset file.
const PRESET_FILE: &str = "usr/lib/systemd/system-preset/10-bootc-imagectl.preset";

/// An `enable` directive of a preset file.
#[derive(Debug, PartialEq, Eq)]
struct Enable {
    unit: String,
    /// The instance names to enable, for a template unit.
    instances: Vec<String>,
}

impl fmt::Display for Enable {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "enable {}", self.unit)?;
        for instance in &self.instances {
            write!(f, " {instance}")?;
        }
        Ok(())
    }
}

/// The directives that enable the units the image enables but the preset
/// policy disables.
fn enable_directives(
    units: &[UnitFile],
    instances: &BTreeMap<String, BTreeSet<String>>,
) -> Vec<Enable> {
    let mut directives = Vec::new();
    for unit in units
        .iter()
        .filter(|unit| unit.preset == Some(Preset::Disabled))
    {
        match UnitName::from(unit.name.as_str()) {
            // For a template unit, the directive enables only the instances
            // it lists.
            UnitName::Template => {
                if let Some(instances) = instances.get(&unit.name) {
                    directives.push(Enable {
                        unit: unit.name.clone(),
                        instances: instances.iter().cloned().collect(),
                    });
                }
            }
            UnitName::Plain if unit.state == EnablementState::Enabled => {
                directives.push(Enable {
                    unit: unit.name.clone(),
                    instances: Vec::new(),
                });
            }
            _ => {}
        }
    }
    directives
}

/// Write the preset file for the rootfs at `/`.
pub(super) fn finalize(root: &Dir) -> Result<()> {
    debug!("recording enabled units in a preset file");
    root.remove_file_optional(PRESET_FILE)
        .with_context(|| format!("removing /{PRESET_FILE}"))?;

    let directives = enable_directives(&units::unit_files()?, &units::enabled_instances(root)?);
    if directives.is_empty() {
        debug!("the preset policy enables every unit the image enables");
        return Ok(());
    }

    let mut content = String::from("# Generated by bootc-imagectl. Do not edit.\n");
    for directive in &directives {
        content.push_str(&directive.to_string());
        content.push('\n');
    }
    root.create_dir_all(PRESET_DIR)?;
    root.write(PRESET_FILE, content)
        .with_context(|| format!("writing /{PRESET_FILE}"))?;
    info!("recorded {} units in /{PRESET_FILE}", directives.len());
    Ok(())
}

#[cfg(test)]
mod tests {
    use indoc::indoc;

    use super::*;

    #[test]
    fn enables_units_disabled_by_preset_policy() -> Result<()> {
        let units: Vec<UnitFile> = serde_json::from_str(indoc! {r#"
            [
              {"unit_file": "sshd.service", "state": "enabled", "preset": "enabled"},
              {"unit_file": "systemd-networkd.service", "state": "enabled", "preset": "disabled"},
              {"unit_file": "remote-integritysetup.target", "state": "disabled", "preset": "enabled"},
              {"unit_file": "podman.service", "state": "disabled", "preset": "disabled"},
              {"unit_file": "systemd-journald.service", "state": "static", "preset": null},
              {"unit_file": "getty@.service", "state": "enabled", "preset": "enabled"},
              {"unit_file": "serial-getty@.service", "state": "indirect", "preset": "disabled"},
              {"unit_file": "container-getty@.service", "state": "disabled", "preset": "disabled"},
              {"unit_file": "foo.service", "state": "something-new", "preset": "ignored"}
            ]
        "#})?;
        let instances = BTreeMap::from([
            (
                "getty@.service".to_owned(),
                BTreeSet::from(["tty2".to_owned()]),
            ),
            (
                "serial-getty@.service".to_owned(),
                BTreeSet::from(["ttyS0".to_owned(), "ttyS1".to_owned()]),
            ),
        ]);
        let directives: Vec<String> = enable_directives(&units, &instances)
            .iter()
            .map(ToString::to_string)
            .collect();
        assert_eq!(
            directives,
            [
                "enable systemd-networkd.service",
                "enable serial-getty@.service ttyS0 ttyS1",
            ]
        );
        Ok(())
    }
}
